GET http://localhost:3000/human

###

GET http://localhost:3000/api/human/5f833a4e71dc46386c274929

###

POST http://localhost:3000/api/human HTTP/1.1
content-type: application/json

{
    "name": "Johnn",
    "document": "123.456.789-22"
}

###

DELETE http://localhost:3000/api/human/5f81f3c3714ece6c509ef2b3


###

PATCH http://localhost:3000/api/human/5f833a4e71dc46386c274929
content-type: application/json

{
    "name": "John Wick",
    "document": "123.456.789-22"
}

### 

PATCH http://localhost:3000/api/human/5f833a4e71dc46386c274929
content-type: application/json

{
    "name": "Jonas Brother",
    "document": "123.456.789-21"
}
